// Code generated by protoc-gen-iyfiysi at 2021 Jun 17
// DO NOT EDIT.

package service

import (
	"google.golang.org/grpc"
	"iyfiysi.com/short_url/proto"
)

// ShortUrlServiceImpl ...
type ShortUrlServiceImpl struct{}

// DoRegister 注册服务
func DoRegister(grpcServer *grpc.Server) (err error) {
	//本地服务注册
	{
		s := &ShortUrlServiceImpl{}
		proto.RegisterShortUrlServiceServer(grpcServer, s)
	}

	return
}
