// Code generated by protoc-gen-iyfiysi at 2021 May 20
// DO AS YOU WANT

package service

import (
	"context"
	"iyfiysi.com/short_url/internal/pkg/service"
	pb "iyfiysi.com/short_url/proto"
)

// Encode ... @TODO
func (s *ShortUrlServiceImpl) Encode(
	ctx context.Context, req *pb.EncodeRequest) ( //request param
	rsp *pb.EncodeResponse, err error) { //response

	rsp = &pb.EncodeResponse{}
	shortUrl, err := service.EncodeMgr().Encode(req.Link)
	if err != nil {
		rsp.RetCode = -1
		rsp.RetMsg = err.Error()
		rsp.MsgShow = ""
		return
	}
	rsp.RetCode = 0
	rsp.RetMsg = "success"
	rsp.MsgShow = "success"
	rsp.ShortUrl = shortUrl
	return
}
