// Code generated by protoc-gen-iyfiysi at 2021 May 20
// DO AS YOU WANT

package service

import (
	"context"
	"iyfiysi.com/short_url/internal/pkg/service"
	pb "iyfiysi.com/short_url/proto"
)

// EncodeWithPhrase ... @TODO
func (s *ShortUrlServiceImpl) EncodeWithPhrase(
	ctx context.Context, req *pb.EncodeWithPhraseRequest) ( //request param
	rsp *pb.EncodeWithPhraseResponse, err error) { //response

	rsp = &pb.EncodeWithPhraseResponse{}
	shortUrl, err := service.PhraseEncodeMgr().Encode(req.Phrase, req.Link)
	if err != nil {
		rsp.RetCode = -1
		rsp.RetMsg = err.Error()
		rsp.MsgShow = ""
		return
	}
	rsp.RetCode = 0
	rsp.RetMsg = "success"
	rsp.MsgShow = "success"
	rsp.ShortUrl = shortUrl
	return
}
