// Code generated by protoc-gen-iyfiysi at 2021 May 19
// DO AS YOU WANT

package service

import(
	"context"
	pb "iyfiysi.com/short_url/proto"
)

// PingPong ... @TODO
func (s *ShortUrlServiceImpl) PingPong(
    ctx context.Context, req *pb.PingRequest)( //request param
    rsp *pb.PongResponse, err error) { //response

	rsp =&pb.PongResponse{}
	return
}