// Code generated by protoc-gen-iyfiysi at 2021 May 20
// DO AS YOU WANT

package service

import (
	"context"
	"iyfiysi.com/short_url/internal/pkg/service"
	pb "iyfiysi.com/short_url/proto"
)

// Decode ... @TODO
func (s *ShortUrlServiceImpl) Decode(
	ctx context.Context, req *pb.DecodeRequest) ( //request param
	rsp *pb.DecodeResponse, err error) { //response

	rsp = &pb.DecodeResponse{}
	link, err := service.DecodeMgr().Decode(req.ShortCode)
	if err != nil {
		rsp.RetCode = -1
		rsp.RetMsg = err.Error()
		return
	}
	rsp.RetCode = 0
	rsp.RetMsg = "success"
	rsp.Link=link

	return
}
