// Code generated by protoc-gen-iyfiysi at 2021 May 20
// DO AS YOU WANT

package service

import (
	"context"
	"iyfiysi.com/short_url/internal/pkg/service"
	pb "iyfiysi.com/short_url/proto"
)

// Ban ... @TODO
func (s *ShortUrlServiceImpl) Ban(
	ctx context.Context, req *pb.BanRequest) ( //request param
	rsp *pb.BanResponse, err error) { //response

	rsp = &pb.BanResponse{}
	err = service.UrlInfoMgr().Ban(req.ShortCode)
	if err != nil {
		rsp.RetCode = -1
		rsp.RetMsg = err.Error()
		rsp.MsgShow = ""
		return
	}
	rsp.RetCode = 0
	rsp.RetMsg = "success"
	rsp.MsgShow = "success"
	return
}
