{
 "title": "iyfiysi-iyfiysi.com/short_url",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "VarProject", "query": "iyfiysi.com/short_url" }
  ]
 },
 "panels": [
  { "title": "业务总览", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "活动进程",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(process_start_time_seconds{role=\"gateway\",project=\"$VarProject\"})",
     "legendFormat": "gateway"
    },
    {
     "expr": "count(process_start_time_seconds{role=\"server\",project=\"$VarProject\"})",
     "legendFormat": "server"
    }
   ]
  },
  {
   "title": "最近一天编码解码总数统计",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(gateway_http_total{project=\"$VarProject\",http_path=\"/encode/v1\"}[24h])) by (http_status)",
     "legendFormat": "encode"
    },
    {
     "expr": "sum(increase(gateway_http_total{http_method=\"GET\",http_status=\"302\"}[24h])) by (http_status) ",
     "legendFormat": "decode"
    }
   ]
  },
  { "title": "gateway", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "http方法时均请求(qps)",
   "type": "graph",
   "description": "http方法时均请求，统计周期为秒时候，为qps",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(gateway_http_total{project=\"$VarProject\",role=\"gateway\"}[$__interval])) by (http_path)",
     "legendFormat": "{{http_path}}"
    }
   ]
  },
  {
   "title": "http状态码统计",
   "type": "graph",
   "description": "http状态码统计",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(gateway_http_total{project=\"$VarProject\",role=\"gateway\"}[24h])) by (http_status)",
     "legendFormat": "{{http_status}}"
    }
   ]
  },
  {
   "title": "grpc方法成功率",
   "type": "graph",
   "description": "统计每个方法的成功率",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_client_handled_total{project=\"$VarProject\",role=\"gateway\",grpc_code=\"OK\"}[$__interval])) by (grpc_method)/sum(rate(grpc_client_handled_total{project=\"$VarProject\",role=\"gateway\"}[$__interval])) by (grpc_method)",
     "legendFormat": "x-succ-{{grpc_method}}"
    },
    {
     "expr": "sum(rate(grpc_client_handled_total{project=\"$VarProject\",role=\"gateway\",grpc_code!=\"OK\"}[$__interval])) by (grpc_method,grpc_code)",
     "legendFormat": "y-err-{{grpc_method}}-{{grpc_code}}"
    }
   ]
  },
  {
   "title": "http耗时统计",
   "type": "graph",
   "description": "处理耗时统计，tp99,tp90,tp75,tp50",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 18 },
   "yaxes": [
    { "format": "s", "label": "request" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99,sum(rate(http_handling_seconds_bucket{project=\"$VarProject\",role=\"gateway\"}[$__interval])) by (http_path,le))",
     "legendFormat": "tp99-{{http_path}}"
    },
    {
     "expr": "histogram_quantile(0.90,sum(rate(http_handling_seconds_bucket{project=\"$VarProject\",role=\"gateway\"}[$__interval])) by (http_path,le))",
     "legendFormat": "tp90-{{http_path}}"
    },
    {
     "expr": "histogram_quantile(0.75,sum(rate(http_handling_seconds_bucket{project=\"$VarProject\",role=\"gateway\"}[$__interval])) by (http_path,le))",
     "legendFormat": "tp90-{{http_path}}"
    },
    {
     "expr": "histogram_quantile(0.50,sum(rate(http_handling_seconds_bucket{project=\"$VarProject\",role=\"gateway\"}[$__interval])) by (http_path,le))",
     "legendFormat": "tp50-{{http_path}}"
    }
   ]
  },
  {
   "title": "网关时均请求",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_client_handled_total{project=\"$VarProject\",role=\"gateway\"}[$__interval])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "goroutine",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 5, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{project=\"$VarProject\",role=\"gateway\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "实例内存",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 11, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{project=\"$VarProject\",role=\"gateway\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "服务器时均请求",
   "type": "graph",
   "description": "服务器某段时间内，处理的请求数量",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{project=\"$VarProject\",role=\"server\"}[$__interval])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "方法耗时统计",
   "type": "graph",
   "description": "处理耗时统计，tp99,tp90,tp75,tp50",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 34 },
   "yaxes": [
    { "format": "short", "label": "request" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99,sum(rate(grpc_server_handling_seconds_bucket{project=\"$VarProject\",role=\"server\",grpc_type=\"unary\"}[$__interval])) by (grpc_method,le))",
     "legendFormat": "y-tp99-{{grpc_method}}"
    },
    {
     "expr": "histogram_quantile(0.90,sum(rate(grpc_server_handling_seconds_bucket{project=\"$VarProject\",role=\"server\",grpc_type=\"unary\"}[$__interval])) by (grpc_method,le))",
     "legendFormat": "y-tp90-{{grpc_method}}"
    },
    {
     "expr": "histogram_quantile(0.75,sum(rate(grpc_server_handling_seconds_bucket{project=\"$VarProject\",role=\"server\",grpc_type=\"unary\"}[$__interval])) by (grpc_method,le))",
     "legendFormat": "y-tp90-{{grpc_method}}"
    },
    {
     "expr": "histogram_quantile(0.50,sum(rate(grpc_server_handling_seconds_bucket{project=\"$VarProject\",role=\"server\",grpc_type=\"unary\"}[$__interval])) by (grpc_method,le))",
     "legendFormat": "y-tp50-{{grpc_method}}"
    }
   ]
  },
  {
   "title": "方法时均请求(qps)",
   "type": "graph",
   "description": "方法时均请求，统计周期为秒时候，为qps",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{project=\"$VarProject\",role=\"server\"}[$__interval])) by (grpc_method)",
     "legendFormat": "{{grpc_method}}"
    }
   ]
  },
  {
   "title": "方法成功率",
   "type": "graph",
   "description": "统计每个方法的成功率",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 42 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{project=\"$VarProject\",role=\"server\",grpc_code=\"OK\"}[$__interval])) by (grpc_method)/sum(rate(grpc_server_handled_total{project=\"$VarProject\",role=\"server\"}[$__interval])) by (grpc_method)",
     "legendFormat": "x-succ-{{grpc_method}}"
    },
    {
     "expr": "sum(rate(grpc_server_handled_total{project=\"$VarProject\",role=\"server\",grpc_code!=\"OK\"}[$__interval])) by (grpc_method,grpc_code)",
     "legendFormat": "err-{{grpc_method}}-{{grpc_code}}"
    }
   ]
  },
  {
   "title": "goroutines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{project=\"$VarProject\",role=\"server\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "实例内存",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{project=\"$VarProject\",role=\"server\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}